sonar.projectKey=kanni5353_tinyccTest
sonar.organization=kanni5353
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}

sonar.projectName=TinyCC C Project
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.cfamily.build-wrapper-output=bw-output
sonar.exclusions=**/*.py,tests/**,docs/**
